import type { SkillDef } from "./types";

/** Indian cities: canonical name → spellings to look for */
export const INDIAN_CITIES: { name: string; aliases: string[] }[] = [
  { name: "Bangalore", aliases: ["Bengaluru", "Bangalore", "Banglore"] },
  { name: "Mumbai", aliases: ["Mumbai", "Bombay"] },
  { name: "Navi Mumbai", aliases: ["Navi Mumbai"] },
  { name: "Thane", aliases: ["Thane"] },
  { name: "Delhi", aliases: ["New Delhi", "Delhi"] },
  { name: "Gurgaon", aliases: ["Gurugram", "Gurgaon"] },
  { name: "Noida", aliases: ["Greater Noida", "Noida"] },
  { name: "Ghaziabad", aliases: ["Ghaziabad"] },
  { name: "Faridabad", aliases: ["Faridabad"] },
  { name: "Hyderabad", aliases: ["Hyderabad", "Secunderabad"] },
  { name: "Chennai", aliases: ["Chennai", "Madras"] },
  { name: "Pune", aliases: ["Pune", "Poona", "Pimpri-Chinchwad", "Pimpri Chinchwad"] },
  { name: "Kolkata", aliases: ["Kolkata", "Calcutta"] },
  { name: "Ahmedabad", aliases: ["Ahmedabad"] },
  { name: "Gandhinagar", aliases: ["Gandhinagar"] },
  { name: "Surat", aliases: ["Surat"] },
  { name: "Vadodara", aliases: ["Vadodara", "Baroda"] },
  { name: "Jaipur", aliases: ["Jaipur"] },
  { name: "Chandigarh", aliases: ["Chandigarh", "Mohali", "Panchkula"] },
  { name: "Lucknow", aliases: ["Lucknow"] },
  { name: "Kanpur", aliases: ["Kanpur"] },
  { name: "Indore", aliases: ["Indore"] },
  { name: "Bhopal", aliases: ["Bhopal"] },
  { name: "Nagpur", aliases: ["Nagpur"] },
  { name: "Nashik", aliases: ["Nashik", "Nasik"] },
  { name: "Coimbatore", aliases: ["Coimbatore"] },
  { name: "Madurai", aliases: ["Madurai"] },
  { name: "Kochi", aliases: ["Kochi", "Cochin", "Ernakulam"] },
  { name: "Trivandrum", aliases: ["Thiruvananthapuram", "Trivandrum"] },
  { name: "Mysore", aliases: ["Mysuru", "Mysore"] },
  { name: "Mangalore", aliases: ["Mangaluru", "Mangalore"] },
  { name: "Visakhapatnam", aliases: ["Visakhapatnam", "Vizag"] },
  { name: "Vijayawada", aliases: ["Vijayawada"] },
  { name: "Bhubaneswar", aliases: ["Bhubaneswar", "Bhubaneshwar"] },
  { name: "Patna", aliases: ["Patna"] },
  { name: "Ranchi", aliases: ["Ranchi"] },
  { name: "Guwahati", aliases: ["Guwahati"] },
  { name: "Dehradun", aliases: ["Dehradun"] },
  { name: "Ludhiana", aliases: ["Ludhiana"] },
  { name: "Amritsar", aliases: ["Amritsar"] },
  { name: "Raipur", aliases: ["Raipur"] },
  { name: "Goa", aliases: ["Panaji", "Goa"] },
  { name: "Varanasi", aliases: ["Varanasi"] },
  { name: "Agra", aliases: ["Agra"] },
  { name: "Jamshedpur", aliases: ["Jamshedpur"] },
  { name: "Rajkot", aliases: ["Rajkot"] },
  { name: "Udaipur", aliases: ["Udaipur"] },
  { name: "Jodhpur", aliases: ["Jodhpur"] },
  { name: "Hubli", aliases: ["Hubballi", "Hubli"] },
  { name: "Tiruchirappalli", aliases: ["Tiruchirappalli", "Trichy"] },
];

/**
 * Built-in skill dictionary (used on its own in tests, and merged with the database master list in
 * the app). Short/ambiguous names (C, R, Go) are only matched inside a Skills section.
 */
export const BUILTIN_SKILLS: SkillDef[] = [
  { name: "JavaScript", aliases: ["JS", "ES6", "ECMAScript"] },
  { name: "TypeScript", aliases: ["TS"] },
  { name: "React", aliases: ["React.js", "ReactJS", "React JS"] },
  { name: "Next.js", aliases: ["NextJS", "Next JS"] },
  { name: "Node.js", aliases: ["Node", "NodeJS", "Node JS"] },
  { name: "Express.js", aliases: ["Express", "ExpressJS"] },
  { name: "Angular", aliases: ["AngularJS", "Angular JS"] },
  { name: "Vue.js", aliases: ["Vue", "VueJS"] },
  { name: "Redux", aliases: [] },
  { name: "HTML", aliases: ["HTML5"] },
  { name: "CSS", aliases: ["CSS3"] },
  { name: "Tailwind CSS", aliases: ["Tailwind"] },
  { name: "Bootstrap", aliases: [] },
  { name: "Java", aliases: ["Core Java", "J2EE"] },
  { name: "Spring Boot", aliases: ["SpringBoot", "Spring"] },
  { name: "Hibernate", aliases: [] },
  { name: "Python", aliases: [] },
  { name: "Django", aliases: [] },
  { name: "Flask", aliases: [] },
  { name: "FastAPI", aliases: [] },
  { name: "C++", aliases: ["CPP"] },
  { name: "C#", aliases: ["CSharp", "C Sharp"] },
  { name: ".NET", aliases: ["dotnet", "ASP.NET", ".NET Core"] },
  { name: "C", aliases: [] },
  { name: "Go", aliases: ["Golang"] },
  { name: "R", aliases: [] },
  { name: "PHP", aliases: [] },
  { name: "Laravel", aliases: [] },
  { name: "Ruby on Rails", aliases: ["Rails"] },
  { name: "Kotlin", aliases: [] },
  { name: "Swift", aliases: [] },
  { name: "Flutter", aliases: [] },
  { name: "React Native", aliases: [] },
  { name: "Android", aliases: [] },
  { name: "iOS", aliases: [] },
  { name: "SQL", aliases: [] },
  { name: "MySQL", aliases: [] },
  { name: "PostgreSQL", aliases: ["Postgres"] },
  { name: "MongoDB", aliases: ["Mongo"] },
  { name: "Oracle", aliases: ["Oracle DB"] },
  { name: "Redis", aliases: [] },
  { name: "AWS", aliases: ["Amazon Web Services"] },
  { name: "Azure", aliases: ["Microsoft Azure"] },
  { name: "GCP", aliases: ["Google Cloud"] },
  { name: "Docker", aliases: [] },
  { name: "Kubernetes", aliases: ["K8s"] },
  { name: "Jenkins", aliases: [] },
  { name: "Terraform", aliases: [] },
  { name: "Git", aliases: ["GitHub", "GitLab"] },
  { name: "Linux", aliases: ["Unix"] },
  { name: "Microservices", aliases: ["Micro services"] },
  { name: "REST APIs", aliases: ["REST", "RESTful", "REST API"] },
  { name: "GraphQL", aliases: [] },
  { name: "Kafka", aliases: ["Apache Kafka"] },
  { name: "Selenium", aliases: [] },
  { name: "Manual Testing", aliases: [] },
  { name: "Automation Testing", aliases: ["Test Automation"] },
  { name: "JIRA", aliases: ["Jira"] },
  { name: "Machine Learning", aliases: ["ML"] },
  { name: "Data Analysis", aliases: ["Data Analytics"] },
  { name: "Power BI", aliases: ["PowerBI"] },
  { name: "Tableau", aliases: [] },
  { name: "Excel", aliases: ["MS Excel", "Advanced Excel", "Microsoft Excel"] },
  { name: "Pandas", aliases: [] },
  { name: "Figma", aliases: [] },
  { name: "Photoshop", aliases: ["Adobe Photoshop"] },
  { name: "AutoCAD", aliases: [] },
  { name: "SAP", aliases: ["SAP FICO", "SAP MM"] },
  { name: "Salesforce", aliases: [] },
  { name: "Tally", aliases: ["Tally ERP", "Tally Prime", "Tally ERP 9"] },
  { name: "GST", aliases: ["GST Filing"] },
  { name: "Accounting", aliases: ["Accounts"] },
  { name: "Taxation", aliases: ["Income Tax", "TDS"] },
  { name: "Financial Reporting", aliases: [] },
  { name: "Recruitment", aliases: ["Talent Acquisition"] },
  { name: "Payroll", aliases: [] },
  { name: "Sales", aliases: ["B2B Sales", "Inside Sales"] },
  { name: "Business Development", aliases: ["BD"] },
  { name: "Digital Marketing", aliases: ["SEO", "SEM"] },
  { name: "Customer Service", aliases: ["Customer Support"] },
  { name: "Communication", aliases: ["Communication Skills"] },
  { name: "Team Management", aliases: ["Team Leadership"] },
  { name: "Patient Care", aliases: [] },
  { name: "ICU", aliases: ["Critical Care"] },
  { name: "Nursing", aliases: [] },
  { name: "Inventory Management", aliases: ["Inventory"] },
  { name: "Supply Chain", aliases: ["Supply Chain Management", "SCM"] },
  { name: "Warehouse Management", aliases: ["WMS"] },
  { name: "Quality Control", aliases: ["QC", "Quality Assurance"] },
];
